### ISSUE TITLE
Cannot run debian8_simple docker image

### ISSUE THREAD

**Issue by nikess** [hove-io/navitia#1722]
Hi. 

Apologies - this is probably a docker issue more than anything else,  but having installed a fresh debian 8 image, installed docker, and tried to run debian8_simple, get error:

docker: layers from manifest don't match image configuration.

Some (https://github.com/docker/distribution/issues/1439) have said downgrading docker client should work, but doesn't for me.   Looks like it may be an issue requiring a re-push to registry?

Thanks.

**Comment by nikess** [comment]
Using tag 1.29 works however.

**Comment by francois-vincent** [comment]
Hi nikess, thank you for reportng :)

I can confirm the docker layers error, I have the same on my dev machine, ubuntu 15.10 and docker 1.12.
Some quick googling seems to point a problem arising from docker versions, which is coherent with the fact that the last Navitia image pushed to dockerhub is a bit old.
The Jenkins task that builds and pushes images is the true culprit, it broke 1 month ago and no one noticed. I fix it and let you know.

Cheers.

**Comment by nikess** [comment]
Thanks!

**Comment by francois-vincent** [comment]
Hi nikess
I think the jenkins pb is fixed and a new debian8_simple image has been pushed to DockerHub. I have successfully been able to pull it on my machine.
Let me know if you have any pb with it !

**Comment by nikess** [comment]
Thanks, works!

**Comment by sign0** [comment]
Hi, it seems the problem is back with the last tag on the docker hub (driven there 13 days). The coverage.osm.pbf of gtfs.zip and are not loaded in Navitia (I use the same docker flags image 1.29 and the same rights on the folders / files). Do you have an idea of the problem?

Thanks

**Comment by francois-vincent** [comment]
Yes I know, sorry about that. Another regression introduced in the build process and removed 2 pytthon dependencies. This should be corrected with the new build/delivery, coming this WE.
I'll check that on monday !

**Comment by francois-vincent** [comment]
Wait, there may be another problem. Actually the buildd of the new docker image was broken in the last release, but it has not been pushed to DockerHub at all, so this can't impact you.
I just removed my old navitia/debian8_simple image, reload and run it, and when I drop a data.zip in /srv/ed/data, the file is not treated.
I'll fix that on next monday !

**Comment by francois-vincent** [comment]
How to test your navitia images

Run it with a mapped data volume:
docker run -d --name navitia --volume /path/to/your/data_folder:/srv/ed/data navitia/debian8_simple

Create a <default> data folder into  /path/to/your/data_folder with rights set to 777:
cd /path/to/your/data_folder && mkdir -m 777 default

drop some data into /path/to/your/data_folder/default and see it being processed:
- a backup directory is created
- a data.nav.lz4 file is created

If you want to check the version of navitia:
docker exec -t navitia dpkg -l | grep navitia 

This worked for me today.
The last version of Navitia (2.16.1) has just ben pushed to DockerHub.

Let me know if something's still wrong for you.
Cheers,
François

**Comment by pbougue** [comment]
If it's confirmed, can we put this in some doc? (maybe on dockerhub?)

**Comment by pbougue** [comment]
I close this feed as https://github.com/CanalTP/navitia-docker-compose is now the recommended way of using Navitia in docker.
